name: Playwright Tests with Docker

on:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (for pushing/pulling images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push image (with caching)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/playwright-tests:cache,mode=max

      # Run Playwright tests inside Docker
      - name: Run Playwright tests
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/playwright-tests:latest
